name: pyrallex
channels:
  - conda-forge
  - defaults
dependencies:
  # Basic conda install
  - python=3.12
  - pip
  - pip:
    - --editable . # install locally
    # Testing
    - pytest
    # Parallelisation
    - joblib
    # Data analysis
    - pandas
