[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"


[project]
name = "pyrallex"
version = "1.0.0"
description = "Easy management of parallel computing jobs using different parallelisation backends."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Jakob Bossek", email = "j.bossek@gmail.com" }
]

dependencies = [
    "joblib>=1.5"
]

classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[project.urls]
Homepage = "https://github.com/jakobbossek/pyrallex"
Repository = "https://github.com/jakobbossek/pyrallex"
Issues = "https://github.com/jakobbossek/pyrallex/issues"


[project.optional-dependencies]
dev = [
    "pytest>=9",
    "pytest-cov>=7",
]


[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]